# Generated by Django 5.2.17 on 2026-09-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuephoto',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='issue_videos/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='issuephoto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='issue_photos/%Y/%m/'),
        ),
    ]
